# Generated by Django 4.2.17 on 2025-01-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(max_length=1000),
        ),
    ]
