# Generated by Django 4.2.17 on 2024-12-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
